### ISSUE TITLE
S3 sink connector fail to integrate with AWS Glue registry

### ISSUE THREAD

**Issue by JKCai** [lensesio/stream-reactor#1150]
# Issue Guidelines

### What version of the Stream Reactor are you reporting this issue for?
6.3.0

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
I'm running the Kafka version under `2.8.2.tiered`.

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
Yes

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes

### What is the expected behaviour?
I am deploying the S3 sink connector using AWS MSK Connect. I have the the Kafka Cluster running on AWS MSK.

I would expect the S3 sink connector is created successfully, and is able to convert messages using the avro converter and write messages to the S3 bucket under avro format.

### What was observed?
I failed to create the S3 sink connector and received the below error.

```
Code: InvalidInput.InvalidConnectorConfiguration
Message: The connector configuration is invalid. Message: Connector configuration is invalid and contains the following 1 error(s): Invalid value com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter for configuration value.converter: Class com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter could not be found.
```
### What is your Connect cluster configuration (connect-avro-distributed.properties)?
n/a

### What is your connector properties configuration (my-connector.properties)?

```
connector.class=io.lenses.streamreactor.connect.aws.s3.sink.S3SinkConnector
aws.region=ap-southeast-2
tasks.max=2
topics=topic-04
connect.s3.kcql=INSERT INTO lenses-connector-bucket-same-region SELECT * FROM `*` STOREAS `AVRO` WITH_FLUSH_COUNT = 1
errors.log.enable=true
connect.s3.aws.region=ap-southeast-2
store.envelope=true

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter

value.converter.schemaAutoRegistrationEnabled=true
value.converter.region=ap-southeast-2
value.converter.avroRecordType=GENERIC_RECORD
value.converter.compatibility=BACKWARD
value.converter.registry.name=test-registry
```

**Comment by stheppi** [comment]
Hi @JKCai,

Kafka Connect's architecture is engineered with extensibility and modularity in mind, promoting decoupling for enhanced flexibility. In this framework, both sinks and sources function as plugins, as do converters responsible for marshaling data to and from bytes. The intentional separation ensures that these components remain agnostic of each other, which is crucial for several reasons. For instance, envision a scenario where a sink must handle every possible data storage format within Kafka. Requiring each sink to accommodate this would not only be impractical but also contrary to best practices in design.

Given this context, it's apparent why the AWS Glue converter is treated as a distinct set of jars, complete with its dependencies. These jars need to be bundled as part of your MSK Connect deployment. You can find a detailed walkthrough on how to bundle the AWS Glue jars [here](https://repost.aws/questions/QUF6gnAQ5xT12K_bqDp-dIPw/aws-glue-schema-registry-and-msk-connect-integration-for-avro-schema)
