### ISSUE TITLE
Applying SMT to S3SourceConnector

### ISSUE THREAD

**Issue by TomVanWemmel** [lensesio/stream-reactor#1246]
# Issue Guidelines
### What version of the Stream Reactor are you reporting this issue for?
6.3.1

### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes

### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
No

### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes

### What is the expected behaviour?
I have an S3 bucket with JSON files that I want to dump into Kafka. 
When I try to apply a SMT to set a key, I'm unable to do so. 

```
{
  "connector.class": "io.lenses.streamreactor.connect.aws.s3.source.S3SourceConnector",
  "connect.s3.aws.auth.mode": "Default",
  "connect.s3.aws.region": "eu-west-1",
  "connect.s3.kcql": "INSERT INTO `topic-for-data-dump` SELECT * FROM `bucket-name:location/in/bucket BATCH=200 STOREAS `JSON` LIMIT 1000",
  "connect.s3.vhost.bucket": "false",
  "errors.log.enable": "true",
  "value.converter": "org.apache.kafka.connect.storage.StringConverter",
  "value.converter.schemas.enable": "false",
  "transforms": "extractKey",
  "transforms.extractKey.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
  "transforms.extractKey.field": "id"
}
```
I'm using a StringConverter as it says in the [Storage to output matrix](https://docs.lenses.io/5.5/connectors/sources/s3sourceconnector/#storage-to-output-matrix)

### What was observed?
The key remains empty, while the value has a JSON format. 

Is it possible to apply SMT on this format?

**Comment by stheppi** [comment]
Hi @TomVanWemmel 

For context, and please bear with me if this is already known information: an SMT (Single Message Transform) for the source is applied after the connector has handed over the records to the Connect framework.

Your SMT transformation specifies that from the record's Key component, the field "id" should be extracted and the Key replaced with this extracted value. For example, if the original Key is:

```json
{"id": "1234", "name": "Tom"}
```

After the transformation, the Key becomes 1234.

Regarding the KCQL settings, you haven't used the envelope mode, so the source will only populate the Value in the record sent to the Connect framework while the Key remains null.

If your Value contains an "id" field that you want to become the Key, you need to apply two transformations:

```json
"transforms": "valueToKey,extractKey",
"transforms.valueToKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
"transforms.valueToKey.fields": "id",
"transforms.extractKey.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.extractKey.field": "id"
```

This setup first takes the field "id" in the Value to the Key `{"id":"1234"}` and then extracts it such that the Key becomes `1234`.

I hope this helps. 

Since this is not an issue with the connector, I will close it.

**Comment by TomVanWemmel** [comment]
Thank you @stheppi for your comment!

> Regarding the KCQL settings, you haven't used the envelope mode, so the source will only populate the Value in the record sent to the Connect framework while the Key remains null.

Correct, the data was not put on S3 with the S3SinkConnector and has no envelope

> If your Value contains an "id" field that you want to become the Key, you need to apply two transformations:
> ```json
> "transforms": "valueToKey,extractKey",
> "transforms.valueToKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
> "transforms.valueToKey.fields": "id",
> "transforms.extractKey.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
> "transforms.extractKey.field": "id"
> ```

That has been one of the options that I tried, but it results in an error from Kafka Connect
```
org.apache.kafka.connect.errors.DataException: 
Only Struct objects supported for [copying fields from value to key], found: java.lang.String
...
```
My assumption was that `STOREAS JSON` would create a Struct.

**Comment by stheppi** [comment]
Hi @TomVanWemmel,

The connector does not handle the transformation from text to JSON to Struct due to performance considerations. Parsing the JSON text, converting it to a struct, and then serializing it back to text incurs significant CPU and memory costs. Additionally, most use cases for JSON with the connector involve simply passing the data through to the Kafka message.

For now, I recommend implementing an SMT (Single Message Transform) which converts the text Json to Struct. I'll add this to our backlog. Alternatively, a custom SMT that uses regex to extract the ID and store it as the key could also be a viable solution.
