### ISSUE TITLE
No artifacts on maven central after 1.2 version

### ISSUE THREAD

**Issue by Chrisss93** [lensesio/stream-reactor#824]
Hi, would it be possible to resume publishing release artifacts back to maven central? I see this was originally requested in #5 (and implemented in ba56209701ebb64b009a04b105b4fffc5299eae9).

The maven-publish plugin as well as the `uploadArchives` task are still present in the `build.gradle` file (though #478 incidentally seems to have marked this task to execute unconditionally cb25560544e69231668c935f56e3519a136e37dd). A few commits after that #478 was merged, the 1.2.1 release was cut and there have been no new maven artifacts ever since. Is this a known/intentional change?

**Comment by andmarios** [comment]
Hello Chris. Unfortunately, we cannot do it because fat or shadowed jars are a nightmare when it comes to licensing.

We could publish just the connector artifact and then you would have to install all the dependencies manually (tens of 3rd party libs).
Even publishing fat/shadow jars in Github is a bad practice we want to eliminate by switching instead to adding all the dependencies jars in the archive (tar.gz) of each connector.

**Comment by Lucas3oo** [comment]
Hi
Regardless of if we uses your fat jars or let Gradle/Maven fetch all the dependencies we as a consumers needs to track all the licenses on the third party jars. We need to generate SBOM so maybe it is even better for consumer of you jut push the connectors to maven central?
